### ISSUE TITLE
No module named 'version' --scikits.audiolab

### ISSUE THREAD

**Issue by tiankong-hut** [buriburisuri/speech-to-text-wavenet#106]
Traceback (most recent call last):
  File "/home/chuwei/disk1/PycharmProjects/speech-to-text-wavenet/preprocess.py", line 6, in <module>
    import scikits.audiolab
  File "/home/chuwei/disk1/anaconda2/envs/New1/lib/python3.6/site-packages/scikits/audiolab/__init__.py", line 22, in <module>
    from version import version as _version
ModuleNotFoundError: No module named 'version'

**Comment by dizzyname** [comment]
I don't see this error on python 2.7, maybe this link can help you. 

https://stackoverflow.com/questions/39130957/importerror-no-module-named-version-when-importing-mechanize

OR you can using virtual environtment for the python and library

**Comment by atanumandal0491** [comment]
just open the file "/home/chuwei/disk1/anaconda2/envs/New1/lib/python3.6/site-packages/scikits/audiolab/init.py" comment out "from version import version as _version" in the next line just wright the version in ' '.

**Comment by asjir** [comment]
In case someone else is stuck on it.
Delete the scikits.audiolab import
If you're not using Libri dataset - just delete the function 'preprocess_libri'. 
Otherwise, convert them from flacs to e.g. wavs, and modify replace the audiolab flac load with librosa wav load.

**Comment by rick-wang-musetalk** [comment]
dose scikits.audiolab only work with python2.7? i have got enough error!

**Comment by YuLong-Liang** [comment]
the exception `no module named 'version'` happens with python 3.5, so i try to create python=2.7 virtual env.
run call `pip install librosa==0.5.0` with pip=9.0.1 and python=2.7.13, the error  is as follow:
`  Downloading http://pypi.doubanio.com/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting singledispatch; python_version < "3.4" (from numba>=0.32->resampy>=0.1.2->librosa==0.5.0)
  Downloading http://pypi.doubanio.com/packages/3f/09/2a17c6505a8373229cb3de6161e3af74ff90afcf4516719aa6cf32fad151/singledispatch-3.7.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3.4" (from numba>=0.32->resampy>=0.1.2->librosa==0.5.0)
  Downloading http://pypi.doubanio.com/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite ... error
  Complete output from command E:\Anaconda3\envs\speech_to_text_wavenet\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\11347\\appdata\\local\\temp\\pip-build-sr4vrd\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\11347\appdata\local\temp\tmp3dhvalpip-wheel- --python-tag cp27:
  running bdist_wheel
  E:\Anaconda3\envs\speech_to_text_wavenet\python.exe c:\users\11347\appdata\local\temp\pip-build-sr4vrd\llvmlite\ffi\build.py
    File "c:\users\11347\appdata\local\temp\pip-build-sr4vrd\llvmlite\ffi\build.py", line 122
      raise ValueError(msg.format(_ver_check_skip)) from e
                                                       ^
  SyntaxError: invalid syntax
  error: command 'E:\\Anaconda3\\envs\\speech_to_text_wavenet\\python.exe' failed with exit status 1

  ----------------------------------------
  Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, funcsigs, singledispatch, enum34, numba, resampy, decorator, audioread, scikit-learn, joblib, librosa
  Running setup.py install for llvmlite ... error
    Complete output from command E:\Anaconda3\envs\speech_to_text_wavenet\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\11347\\appdata\\local\\temp\\pip-build-sr4vrd\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\11347\appdata\local\temp\pip-wjz8iy-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file c:\users\11347\appdata\local\temp\pip-build-sr4vrd\llvmlite\llvmlite/_version.py {'version': '0.32.1', 'full': 'aa11b129c0b55973067422397821ae6d44fa5e70'}
    running build_ext
    E:\Anaconda3\envs\speech_to_text_wavenet\python.exe c:\users\11347\appdata\local\temp\pip-build-sr4vrd\llvmlite\ffi\build.py
      File "c:\users\11347\appdata\local\temp\pip-build-sr4vrd\llvmlite\ffi\build.py", line 122
        raise ValueError(msg.format(_ver_check_skip)) from e
                                                         ^
    SyntaxError: invalid syntax
    error: command 'E:\\Anaconda3\\envs\\speech_to_text_wavenet\\python.exe' failed with exit status 1

    ----------------------------------------
Command "E:\Anaconda3\envs\speech_to_text_wavenet\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\11347\\appdata\\local\\temp\\pip-build-sr4vrd\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\11347\appdata\local\temp\pip-wjz8iy-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\11347\appdata\local\temp\pip-build-sr4vrd\llvmlite\
You are using pip version 9.0.1, however version 22.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

running `pip3 install librosa==0.5.0` can success, but librosa can not been imported and seen in `pip list`
