### ISSUE TITLE
Problem occurs when running the train.py

### ISSUE THREAD

**Issue by ghost** [buriburisuri/speech-to-text-wavenet#107]
I just cannot make sure what "extract them in the 'asset/data/VCTK-Corpus', 'asset/data/LibriSpeech' and 'asset/data/TEDLIUM_release2' directories." means. I don't have the directories at all so I manually build it. I am not sure whether I build it in the right place.

Here is the Traceback I got:

```
Traceback (most recent call last):
  File "recognize.py", line 63, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('asset/train'))
  File "/home/username/ENTER/envs/tensorflow1.0.0/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/username/ENTER/envs/tensorflow1.0.0/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/username/ENTER/envs/tensorflow1.0.0/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/username/ENTER/envs/tensorflow1.0.0/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/username/ENTER/envs/tensorflow1.0.0/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/home/username/ENTER/envs/tensorflow1.0.0/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
SystemError: <built-in function TF_Run> returned a result with an error set

```

**Comment by atanumandal0491** [comment]
create a folder "asset" then "data" under "asset" then extract the corpus under "data"
