### ISSUE TITLE
Train.py error

### ISSUE THREAD

**Issue by blueringio** [buriburisuri/speech-to-text-wavenet#11]
Ubuntu 16.04.1, Tensorflow 0.11.head, CUDA 8.0, CUDADNN 5.1.5

gpu@gpu:~/speech-to-text-wavenet$ python -c 'import tensorflow as tf; print(tf.__version__)' 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
0.11.head

ERROR:
gpu@gpu:~/speech-to-text-wavenet$ python train.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
INFO:tensorflow:1129:15:23:18.141:data.py:60] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    z, s = res_block(z, size=7, rate=r)
  File "train.py", line 52, in res_block
    conv_gate = tensor.sg_aconv1d(size=size, rate=rate,  act='sigmoid', bn=True)
  File "/home/gpu/.local/lib/python2.7/site-packages/sugartensor/sg_main.py", line 149, in wrapper
    out = func(tensor, opt)
  File "/home/gpu/.local/lib/python2.7/site-packages/sugartensor/sg_layer.py", line 91, in sg_aconv1d
    w = init.he_uniform('W', (1, opt.size, opt.in_dim, opt.dim))
  File "/home/gpu/.local/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 31, in he_uniform
    return uniform(name, shape, s, dtype)
  File "/home/gpu/.local/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 20, in uniform
    initializer=tf.random_uniform_initializer(minval=-scale, maxval=scale))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 632, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable layers/aconv1d_1/W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/gpu/.local/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 20, in uniform
    initializer=tf.random_uniform_initializer(minval=-scale, maxval=scale))
  File "/home/gpu/.local/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 31, in he_uniform
    return uniform(name, shape, s, dtype)
  File "/home/gpu/.local/lib/python2.7/site-packages/sugartensor/sg_layer.py", line 91, in sg_aconv1d
    w = init.he_uniform('W', (1, opt.size, opt.in_dim, opt.dim))

**Comment by buriburisuri** [comment]
@blueringio  Please refer issue #3.

**Comment by Treehouseman** [comment]
The issue here might more be what I'm facing right now, the binaries you link are simply for cuda7.5, which is fine and all, but for those of us with newer GPU's, like my GTX 1060, I can't use CUDA 7.5. The minimum version of CUDA is 8.0 and Cudnn 5.1.5, The 0.11.HEAD tensorflow is compatible with this, but results in the above error. I have tested the cuda examples in tensorflow and confirmed it funcitons, but the updated code does not work seemingly with sugartensor. The error code points fingers at sugartensor and tensorflow. Until it's updated, I can only work with CPU.

**Comment by chrisconley** [comment]
I'm seeing the same thing on fresh Anaconda environment on Mac 10.12.1 with Tensorflow 0.11.0 CPU.

``` bash
conda create -n stf27 python=2.7 anaconda
source activate stf27
python --version
# Python 2.7.12 :: Continuum Analytics, Inc.
conda --version
# conda 4.2.9
```

``` bash
curl https://bootstrap.pypa.io/ez_setup.py -o - | python 
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl
pip install --upgrade $TF_BINARY_URL
pip install sugartensor
pip install tqdm
pip install librosa
pip install pandas
python train.py 
```

Results in
```
INFO:tensorflow:1129:22:03:58.455:data.py:60] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    z, s = res_block(z, size=7, rate=r)
  File "train.py", line 49, in res_block
    conv_filter = tensor.sg_aconv1d(size=size, rate=rate, act='tanh', bn=True, name='filter_conv')
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/sugartensor/sg_main.py", line 149, in wrapper
    out = func(tensor, opt)
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/sugartensor/sg_layer.py", line 91, in sg_aconv1d
    w = init.he_uniform('W', (1, opt.size, opt.in_dim, opt.dim))
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 31, in he_uniform
    return uniform(name, shape, s, dtype)
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 20, in uniform
    initializer=tf.random_uniform_initializer(minval=-scale, maxval=scale))
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1022, in get_variable
    custom_getter=custom_getter)
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 849, in get_variable
    custom_getter=custom_getter)
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 345, in get_variable
    validate_shape=validate_shape)
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 330, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 633, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable layers/filter_conv/W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 20, in uniform
    initializer=tf.random_uniform_initializer(minval=-scale, maxval=scale))
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/sugartensor/sg_initializer.py", line 31, in he_uniform
    return uniform(name, shape, s, dtype)
  File "/Users/chris/anaconda3/envs/tf27/lib/python2.7/site-packages/sugartensor/sg_layer.py", line 91, in sg_aconv1d
    w = init.he_uniform('W', (1, opt.size, opt.in_dim, opt.dim))
```

**Comment by buriburisuri** [comment]
Would you try after deleting 'asset/train' directory with command 'rm -rf asset/train' in the main directory if exists.

**Comment by chrisconley** [comment]
Thanks for the reply - `asset/train` doesn't exist. All I have in `asset` is the data set in `asset/data`.

**Comment by blueringio** [comment]
Same here. asset/train does not exist but asset/data does.

**Comment by buriburisuri** [comment]
@blueringio @Treehouseman @chrisconley 

I finally find out the cause of this issue.  In tensorflow(>= 0.11), tf.get_collection(tf.GraphKeys.VARIABLES) always returns empty list.  And tensorflow 0.12rc deprecated tf.all_variables(), so I replaced tf.get_collection(tf.GraphKeys.VARIABLES)  with tf.global_variables() ( new in 0.12 ).  

I'll patch sugartensor soon, and notify you when finished.

Thank you for your information and patience.

**Comment by buriburisuri** [comment]
@blueringio @Treehouseman @chrisconley

I've updated sugartensor to v0.0.2.0.  You can upgrade by 'pip install --upgrade sugartensor'
(You should update tensorflow to version 0.12rc.)

I hope this will fix your problem.

**Comment by blueringio** [comment]
Yes, fixed. Upgraded sugartensor, remained at tf 0.11.head and can confirm it is working, many thanks. Look forward to more testing with sugartensor.

Will test with 0.12.rc as well.
