### ISSUE TITLE
Recognise.py error

### ISSUE THREAD

**Issue by atanumandal0491** [buriburisuri/speech-to-text-wavenet#113]
While testing the model getting the error. I have used pretrained model. 

python recognize.py --file p364_001.wav 
Traceback (most recent call last):
  File "recognize.py", line 53, in <module>
    mfcc = np.transpose(np.expand_dims(librosa.feature.mfcc(wav, 16000), axis=0), [0, 2, 1])
  File "/usr/local/lib/python2.7/dist-packages/librosa/feature/spectral.py", line 1279, in mfcc
    S = power_to_db(melspectrogram(y=y, sr=sr, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/librosa/feature/spectral.py", line 1371, in melspectrogram
    mel_basis = filters.mel(sr, n_fft, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/librosa/filters.py", line 238, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,1025) (0,) 

Please help through the issues

**Comment by profsatwinder** [comment]
@atanumandal0491 hi there. I have the same problem. have you solved it?

**Comment by atanumandal0491** [comment]
Yes my problem is solved.

**Comment by nandini-menon** [comment]
This error appeared because the librosa version is deprecated.
Just run 
<pre><code>
pip install --upgrade librosa
</code></pre>
and then the program should work..
It worked for me..
