### ISSUE TITLE
Train.py error

### ISSUE THREAD

**Issue by zouwei02** [buriburisuri/speech-to-text-wavenet#12]
ERROR: sugartensor-0.0.1.9/sugartensor/sg_queue.py

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    data = VCTK(batch_size=batch_size)
  File "/mnt/NFS2/zouwei/work/wavenet/speech-to-text-wavenet-master/data.py", line 43, in __init__
    capacity=128, num_threads=32)
  File "/mnt/NFS2/zouwei/tools/env/relays/sugartensor-0.0.1.9/sugartensor/sg_queue.py", line 49, in wrapper
    runner = FuncQueueRunner(enqueue_func, queue, [enqueue_op] * opt.num_threads)
  File "/mnt/NFS2/zouwei/tools/env/relays/sugartensor-0.0.1.9/sugartensor/sg_queue.py", line 69, in __init__
    queue_closed_exception_types, queue_runner_def)
TypeError: __init__() takes at most 6 arguments (7 given

**Comment by buriburisuri** [comment]
Please see issue #1
