### ISSUE TITLE
Numpy missing in requirements.txt

### ISSUE THREAD

**Issue by KarimJedda** [buriburisuri/speech-to-text-wavenet#17]
steps to reproduce:
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt

ollecting resampy>=0.1.0 (from librosa>=0.4.3->-r requirements.txt (line 3))
  Downloading resampy-0.1.4.tar.gz (442kB)
    100% |████████████████████████████████| 450kB 2.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0v/h83f7t897wnfzkh127v1y0qh3f10dr/T/pip-build-yPf939/resampy/setup.py", line 6, in <module>
        import numpy as np
    ImportError: No module named numpy

**Comment by KarimJedda** [comment]
Forget it, it comes as a tensorflow requirement :)
