### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'shape'

### ISSUE THREAD

**Issue by a00achild1** [buriburisuri/speech-to-text-wavenet#22]
Hi,
I was trying to run train.py, but got the following error:

> Traceback (most recent call last):
  File "train.py", line 79, in <module>
    loss = logit.sg_ctc(target=y, seq_len=seq_len)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_loss.py", line 225, in sg_ctc
    out = tf.nn.ctc_loss(tensor, opt.target.sg_to_sparse(), opt.seq_len, time_major=False)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_transform.py", line 256, in sg_to_sparse
    shape=tf.shape(tensor).sg_cast(dtype=tf.int64))
TypeError: __init__() got an unexpected keyword argument 'shape'

I'm using Ubuntu 14.04LTS
GeForce GTX 970/PCIe/SSE2
tensorflow 0.12.1
sugartensor 0.0.2.3

Any help will be very appreciated!

**Comment by a00achild1** [comment]
After tracing the documentation of the master branch of tensorflow, 
I solve this problem by changing `shape` to `dense_shape`

**Comment by buriburisuri** [comment]
@a00achild1 Sorry for late reply.  Thanks for your information.  I'll check this and patch.
