### ISSUE TITLE
Tensor name "lyr-aconv1d_1/mean" not found in checkpoint files asset/train/ckpt\model-020-45480

### ISSUE THREAD

**Issue by josephwinston** [buriburisuri/speech-to-text-wavenet#25]
I'm attempting to run ```python recognize.py --file asset/data/wav48/p225/p225_003.wav``` on:

* Windows 7
* Python 3.5.2
* TensorFlow 0.12.1
* sugartensor 0.0.2.3
* pandas 0.19.2
* librosa 0.4.3
* tqdm 4.10.0-9175881

When I try to convert the speech in p225_003.wav into text, I receive the following traceback:

```python
(tensorflow) D:\home\josephwinston\src\Remote\GIT\speech-to-text-wavenet>python recognize.py --file asset/data/wav48/p225/p225_003.wav
INFO:tensorflow:0109:15:54:36.033:data.py:60] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lyr-aconv1d_1/mean" not found in checkpoint files asset/train/ckpt\model-020-45480
         [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "recognize.py", line 102, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('asset/train/ckpt'))
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "lyr-aconv1d_1/mean" not found in checkpoint files asset/train/ckpt\model-020-45480
         [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]

Caused by op 'save/RestoreV2_5', defined at:
  File "recognize.py", line 101, in <module>
    saver = tf.train.Saver()
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 624, in build
    restore_sequentially, reshape)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\hb55683\AppData\Local\Continuum\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "lyr-aconv1d_1/mean" not found in checkpoint files asset/train/ckpt\model-020-45480
         [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
````

The file exists:

```
ls -l asset/train/ckpt/model-020-45480
-rw-rw-r-- 1 HB55683 Domain Users 29919277 Nov 25 11:16 asset/train/ckpt/model-020-45480
```

The pre-trained models are from <(https://drive.google.com/open?id=0B3ILZKxzcrUyVWwtT25FemZEZ1k>

Running ```grep``` on ```asset/train/ckpt/model-020-45480``` shows that ```lyr-aconv1d_1``` is not in the pickle.  

Could there perhaps be an issue with the saved models since they are not being correctly restored?

**Comment by josephwinston** [comment]
Duplicate issue <https://github.com/buriburisuri/speech-to-text-wavenet/issues/19>
