### ISSUE TITLE
Error running recognize.py after training (and with pretrained models)

### ISSUE THREAD

**Issue by jeremyblalock** [buriburisuri/speech-to-text-wavenet#28]
**Note:** Using tensorflow **v0.12.1**

I downloaded the dataset as instructed in the README into `/data` and was able to successfully run `train.py` through one full epoch (took about 8 hours without GPU with the batch size decreased to 4). And then around the time the second epoch was beginning I attempted to test the results so far by calling:

```
python recognize.py --file asset/data/wav48/p225/p225_001.wav
```

which I had expected to work as expected, since it's running on one of the training examples. But I got the following trace:

```
INFO:tensorflow:0120:10:08:54.924:data.py:41] VCTK vocabulary loaded.
Traceback (most recent call last):
  File "recognize.py", line 102, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('asset/train/ckpt'))
  File "/Users/jeremy/Documents/Other/personal/learning/venv/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/jeremy/Documents/Other/personal/learning/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/Users/jeremy/Documents/Other/personal/learning/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/jeremy/Documents/Other/personal/learning/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/Users/jeremy/Documents/Other/personal/learning/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unable to get element from the feed as bytes.
```

Then, thinking that perhaps my checkpoint was corrupted, I tried downloading the pretrained models as described in the README, but this produced the same error. In a [StackOverflow post](http://stackoverflow.com/questions/41369062/tensorflow-fail-with-unable-to-get-element-from-the-feed-as-bytes-when-attemp) I noticed that a missing `checkpoint` file could cause this problem, but I have a file `asset/train/checkpoint` present, both in the pretrained and live training cases.

Please let me know if you know of anything I can do to get this working!

**Comment by buriburisuri** [comment]
@jeremyblalock  I think that therer's tensorflow and sugartensor version mismatch. Check your checkpoint files in the 'asset/train/checkpoint' or 'asset/train', if the second case, please modify  saver.restore(sess, tf.train.latest_checkpoint('asset/train/ckpt')) to saver.restore(sess, tf.train.latest_checkpoint('asset/train')) at line 102 in the recognize.py

**Comment by jeremyblalock** [comment]
@buriburisuri: Good catch. It seems like the issue was as you said in the fact that the directory structure changed. after changing like 102 of recognize.py everything worked as expected.
