### ISSUE TITLE
Train.py Error

### ISSUE THREAD

**Issue by phongnhhn92** [buriburisuri/speech-to-text-wavenet#3]
I tried to run both train.py and recognize,py but I have the same error like this. Noted that i already place the data or the pre trained model at the right folder. By reading the error, my python might be the problem, please help me to fix it !
/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py:378: UserWarning: tk.pythoninspect is obsolete, and has no effect
  warnings.warn("tk.pythoninspect is obsolete, and has no effect")
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from data import VCTK
  File "/home/phong/speech-to-text-wavenet-master/data.py", line 5, in <module>
    import librosa
  File "/usr/local/lib/python2.7/dist-packages/librosa/__init__.py", line 18, in <module>
    from . import display
  File "/usr/local/lib/python2.7/dist-packages/librosa/display.py", line 30, in <module>
    _matplotlibrc = copy.deepcopy(mpl.rcParams)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 358, in _reconstruct
    y[key] = value
  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 808, in __setitem__
    cval = self.validate[key](val)
  File "/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py", line 95, in validate_bool_maybe_none
    raise ValueError('Could not convert "%s" to boolean' % b)
ValueError: Could not convert "None" to boolean

**Comment by rshravan** [comment]
python -c "import tensorflow; print tensorflow.__version__"
should be 0.11.0 
Just got working with this update. 
On my Mac
`export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl
sudo pip install --upgrade $TF_BINARY_URL'

**Comment by anhncs** [comment]
`I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:1129:11:51:04.747:data.py:60] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    z, s = res_block(z, size=7, rate=r)
  File "train.py", line 52, in res_block
    conv_gate = tensor.sg_aconv1d(size=size, rate=rate,  act='sigmoid', bn=True)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_main.py", line 149, in wrapper
    out = func(tensor, opt)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_layer.py", line 91, in sg_aconv1d
    w = init.he_uniform('W', (1, opt.size, opt.in_dim, opt.dim))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_initializer.py", line 31, in he_uniform
    return uniform(name, shape, s, dtype)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_initializer.py", line 20, in uniform
    initializer=tf.random_uniform_initializer(minval=-scale, maxval=scale))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 632, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable layers/aconv1d_1/W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_initializer.py", line 20, in uniform
    initializer=tf.random_uniform_initializer(minval=-scale, maxval=scale))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_initializer.py", line 31, in he_uniform
    return uniform(name, shape, s, dtype)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_layer.py", line 91, in sg_aconv1d
    w = init.he_uniform('W', (1, opt.size, opt.in_dim, opt.dim))
`

I installed both tf 0.11 & 0.12 and still got this problem.

**Comment by itzikgili** [comment]
You can check your tensorflow version using python 3 with `python -c "import tensorflow as tf; print(tf.__version__)"`
