### ISSUE TITLE
cant find the assets/data directory???

### ISSUE THREAD

**Issue by sidh104** [buriburisuri/speech-to-text-wavenet#33]
Sir,can you help me finding the assets/data directory to put the corpus..... after installation of all dependencies........

**Comment by uralik** [comment]
after you downloaded the VCTK corpus - just create such a directory or make a symlink to the VCTK path there

**Comment by buriburisuri** [comment]
@uralik Thank you.

**Comment by sidh104** [comment]
made a directory asset/train/VCTK corpus now after executing python train.py i got this
root@ubuntu:/home/varsha/Desktop/project/speech-to-text-wavenet-master# python train.py
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    data = VCTK(batch_size=batch_size)
  File "/home/varsha/Desktop/project/speech-to-text-wavenet-master/data.py", line 45, in __init__
    labels, wave_files = self._load_corpus(data_path)
  File "/home/varsha/Desktop/project/speech-to-text-wavenet-master/data.py", line 79, in _load_corpus
    index_col=False, delim_whitespace=True)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4025)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8031)
IOError: File asset/data/speaker-info.txt does not exist
root@ubuntu:/home/varsha/Desktop/project/speech-to-text-wavenet-master#

**Comment by uralik** [comment]
@sidh104 
IOError: File asset/data/speaker-info.txt does not exist -> means that file is not there, may be you should double check that.

as I see you created another dir VCTK inside train folder. this is wrong. Just check the code.

you should make dir data inside asset, and data should already have the content of VCTK-Corpus files.

**Comment by sidh104** [comment]
we did and now we get this error
root@ubuntu:/home/varsha/Desktop/project/speech-to-text-wavenet-master# python train.py
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    data = VCTK(batch_size=batch_size)
  File "/home/varsha/Desktop/project/speech-to-text-wavenet-master/data.py", line 45, in __init__
    labels, wave_files = self._load_corpus(data_path)
  File "/home/varsha/Desktop/project/speech-to-text-wavenet-master/data.py", line 111, in _load_corpus
    self.max_len = np.max([len(s) for s in sents])
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2252, in amax
    out=out, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
root@ubuntu:/home/varsha/Desktop/project/speech-to-text-wavenet-master#

**Comment by fazalWahid56** [comment]
@sidh104  you need to extract **VCTK-Corpus.tar.gz** directly in **/asset/data** .  Are you using pre-trained model?

**Comment by sidh104** [comment]
@fazalWahid56 we r using the VCTK-corpus and v dnt have any pre-trained model other than that

**Comment by chrislinan** [comment]
@sidh104 if I use the  pre-trained model and I got the error : IOError: File asset/data/speaker-info.txt does not exist  .
what should I do?

**Comment by sidh104** [comment]
@chrislinan u shud put the pre-trained model in asset/data directory just put all the files and folders which is inside VCTK-corpus into assets/data directory
