### ISSUE TITLE
Error: got an unexpected keyword argument 'shape'

### ISSUE THREAD

**Issue by eurismarpires** [buriburisuri/speech-to-text-wavenet#45]
When I run the train.py the following errors appear:

root@7b5e7d552258:~/speech-to-text-wavenet# python train.py 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
INFO:tensorflow:0225:23:49:51.252:data.py:73] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    loss = logit.sg_ctc(target=y, seq_len=seq_len)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_loss.py", line 225, in sg_ctc
    out = tf.nn.ctc_loss(tensor, opt.target.sg_to_sparse(), opt.seq_len, time_major=False)
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/sugartensor/sg_transform.py", line 277, in sg_to_sparse
    shape=tf.shape(tensor).sg_cast(dtype=tf.int64))
TypeError: __init__() got an unexpected keyword argument 'shape'

**Comment by Kyubyong** [comment]
Try replacing `decoded[0].shape` with `decoded[0].dense_shape` in line 80 of `recognize.py' if you're using TF 1.0.

From
y = tf.sparse_to_dense(decoded[0].indices, decoded[0].shape, decoded[0].values) + 1

To
y = tf.sparse_to_dense(decoded[0].indices, decoded[0].dense_shape, decoded[0].values) + 1
