### ISSUE TITLE
ValueError: Shape must be rank 1 but is rank 0 for 'CTCBeamSearchDecoder' (op: 'CTCBeamSearchDecoder') with input shapes: [?,1,28], [].

### ISSUE THREAD

**Issue by eurismarpires** [buriburisuri/speech-to-text-wavenet#46]
When I run the file recognize.py the following errors appear:

 python recognize.py --file asset/data/wav48/p225/p225_003.wav
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
INFO:tensorflow:0225:23:55:48.653:data.py:41] VCTK vocabulary loaded.
Traceback (most recent call last):
  File "recognize.py", line 77, in <module>
    decoded, _ = tf.nn.ctc_beam_search_decoder(logit.sg_transpose(perm=[1, 0, 2]), seq_len, merge_repeated=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/ctc_ops.py", line 258, in ctc_beam_search_decoder
    merge_repeated=merge_repeated))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_ctc_ops.py", line 66, in _ctc_beam_search_decoder
    merge_repeated=merge_repeated, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 1 but is rank 0 for 'CTCBeamSearchDecoder' (op: 'CTCBeamSearchDecoder') with input shapes: [?,1,28], [].

**Comment by IsuruDilhan** [comment]
Got the same error here.

**Comment by cfk1990** [comment]
Same error too.

**Comment by IsuruDilhan** [comment]
I fixed it by just downgrading sugartensor `1.0.0.1` to `0.0.2.3`
`pip install sugartensor==0.0.2.3`

Worked for me.

**Comment by cfk1990** [comment]
I fix it by pip install sugartensor==0.0.2.3, but come up with another error:  


INFO:tensorflow:0306:12:16:00.644:data.py:73] VCTK corpus loaded.(total data=36395, total batch=2274)
Traceback (most recent call last):
  File "/home/frankchen/IdeaProjects/speech-to-text-wavenet/train.py", line 79, in <module>
    loss = logit.sg_ctc(target=y, seq_len=seq_len)
  File "/home/frankchen/anaconda2/envs/ml3/lib/python2.7/site-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/home/frankchen/anaconda2/envs/ml3/lib/python2.7/site-packages/sugartensor/sg_loss.py", line 225, in sg_ctc
    out = tf.nn.ctc_loss(tensor, opt.target.sg_to_sparse(), opt.seq_len, time_major=False)
  File "/home/frankchen/anaconda2/envs/ml3/lib/python2.7/site-packages/sugartensor/sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/home/frankchen/anaconda2/envs/ml3/lib/python2.7/site-packages/sugartensor/sg_transform.py", line 256, in sg_to_sparse
    shape=tf.shape(tensor).sg_cast(dtype=tf.int64))
TypeError: __init__() got an unexpected keyword argument 'shape'

**Comment by Kyubyong** [comment]
Try replacing `dims` with `axis` in line 35 of train.py if you are using TF 1.0. The argument name `dims` has changed to `axis` in many functions.

seq_len = tf.not_equal(x.sg_sum(dims=2), 0.).sg_int().sg_sum(dims=1)

**Comment by kenyeung128** [comment]
thanks @Kyubyong, changing 'dims' to 'axis' works for me

**Comment by ChristofHenkel** [comment]
should be closed now with new version
