### ISSUE TITLE
ValueError in CTCLoss 

### ISSUE THREAD

**Issue by gvoysey** [buriburisuri/speech-to-text-wavenet#47]
Ubuntu 14. 

`python train.py` results in : 

```
INFO:tensorflow:0228:18:35:26.811:data.py:73] VCTK corpus loaded.(total data=36395, total batch=2274)                         
Traceback (most recent call last):                            
  File "train.py", line 79, in <module>                               
    loss = logit.sg_ctc(target=y, seq_len=seq_len)
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/sugartensor/sg_main.py", line 151, in wrapper                         
    out = func(tensor, tf.sg_opt(kwargs))       
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/sugartensor/sg_loss.py", line 226, in sg_ctc                          
    ctc_merge_repeated=opt.merge, time_major=False)                                           
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/ops/ctc_ops.py", line 145, in ctc_loss              
    ctc_merge_repeated=ctc_merge_repeated)    
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 164, in _ctc_loss         
    name=name)        
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op 
    op_def=op_def)    
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2397, in create_op          
    set_shapes_for_outputs(ret)               
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs   
    shapes = shape_func(op)                       
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)                                               
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn       
    debug_python_shape_fn, require_shape_fn)  
  File "/home/gvoysey/.local/share/virtualenvs/speech-to-text-wavenet/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl 
    raise ValueError(err.message)             
ValueError: Shape must be rank 1 but is rank 0 for 'CTCLoss' (op: 'CTCLoss') with input shapes: [?,16,28], [?,2], [?], [].        
```

Any ideas?

```
tensorflow version 1.0.0
sugartensor version 1.0.0.1
```

**Comment by wintor12** [comment]
I got the same error, any ideas

**Comment by gvoysey** [comment]
My hypothesis is that tensorflow's API changed.   If i roll back to tensorflow 0.12.1, i get further than this but it crashes elsewhere.

@buriburisuri : what version of TF did you use for this code?  Also, did you use a CUDA enabled version?

**Comment by gbrouwer** [comment]
Same issue here, with Tensorflow 1.0

**Comment by SunQinyao** [comment]
Same issue here, with Tensorflow 1.0

**Comment by EN10** [comment]
@gvoysey i got it working using tensorflow 0.11.0
see here for details: 
https://github.com/buriburisuri/speech-to-text-wavenet/issues/49

**Comment by Kyubyong** [comment]
Try replacing `dims` with `axis` in line 35 of train.py if you are using TF 1.0. The argument name `dims` has changed to `axis` in many functions.

seq_len = tf.not_equal(x.sg_sum(dims=2), 0.).sg_int().sg_sum(dims=1)

**Comment by saurabhvyas** [comment]
I can confirm I got the same error with evaluate.py , all dependencies are correctly installed (correct versions ) , I tried above solution but didnt work out

**Comment by saurabhvyas** [comment]
```
(tensorflow_old) saurabh@saurabh-MS-7923:~/saurabh/wavenet$ python recognize.py --file  redcolor.wav
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "recognize.py", line 38, in <module>
    decoded, _ = tf.nn.ctc_beam_search_decoder(logit.sg_transpose(perm=[1, 0, 2]), seq_len, merge_repeated=False)
  File "/home/saurabh/tensorflow_old/local/lib/python2.7/site-packages/tensorflow/python/ops/ctc_ops.py", line 258, in ctc_beam_search_decoder
    merge_repeated=merge_repeated))
  File "/home/saurabh/tensorflow_old/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 64, in _ctc_beam_search_decoder
    merge_repeated=merge_repeated, name=name)
  File "/home/saurabh/tensorflow_old/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/saurabh/tensorflow_old/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/home/saurabh/tensorflow_old/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/saurabh/tensorflow_old/local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Shape must be rank 1 but is rank 0
```

**Comment by gvoysey** [comment]
is this still relevant?
