### ISSUE TITLE
ImportError: No module named 'sg_util'

### ISSUE THREAD

**Issue by fosskers** [buriburisuri/speech-to-text-wavenet#5]
I've installed (as far as I know) the Python 3 version of all your dependencies, including Tensorflow.

When running `recognize.py` I get:

```console
colin@yumi ~/c/h/e/speech-to-text-wavenet> python recognize.py --file carlin_disappointed.wav 
Traceback (most recent call last):
  File "recognize.py", line 2, in <module>
    import sugartensor as tf
  File "/usr/lib/python3.5/site-packages/sugartensor/__init__.py", line 5, in <module>
    from sg_util import sg_opt
ImportError: No module named 'sg_util'
```

`sugartensor` is definitely installed. Thoughts?

**Comment by buriburisuri** [comment]
Sorry. Python 3 is not supported not yet. Try 2.7 ver.

**Comment by fosskers** [comment]
Alright, thanks. I'll let you know how it goes.

**Comment by fosskers** [comment]
Almost...

```
Traceback (most recent call last):
  File "recognize.py", line 4, in <module>
    import librosa
  File "/usr/lib/python2.7/site-packages/librosa/__init__.py", line 18, in <module>
    from . import display
  File "/usr/lib/python2.7/site-packages/librosa/display.py", line 21, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/lib/python2.7/site-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/lib/python2.7/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```

**Comment by buriburisuri** [comment]
I find that librosa requires matplotlib.  Sorry but librosa is mandatory for this project and you need to install matplotlib. ( If you have problem with TKinter, then try in the global python env. not in the virtualenv)

**Comment by fosskers** [comment]
Both are already installed actually, in the global environment.

**Comment by buriburisuri** [comment]
@clusterfudge suggested librosa-lite instead of librosa.  Please, refer issue #8.

**Comment by fosskers** [comment]
I'm on Arch Linux, and the solution was to install TK via: `sudo pacman -S tk`

**Comment by AlvinChen13** [comment]
For CentOS, if you encounter the following error, please do:

sudo yum install tk-devel tkinter


  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named Tkinter
