### ISSUE TITLE
Train.py error - ValueError: Shape must be rank 1 but is rank 0 for 'CTCLoss'

### ISSUE THREAD

**Issue by Adamage** [buriburisuri/speech-to-text-wavenet#51]
Exception during training. Can you help? I did not modify the code, just trying to get it running..

INFO:tensorflow:0308:21:40:05.892:data.py:72] VCTK corpus loaded.(total data=36395, total batch=9098)
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'CTCLoss' (op: 'CTCLoss') with input shapes: [?,4,37], [?,2], [?], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/msi/Source/Repos/speech-to-text-wavenet/train.py", line 60, in <module>
    loss = logit.sg_ctc(target=y, seq_len=seq_len)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\sugartensor\sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\sugartensor\sg_loss.py", line 226, in sg_ctc
    ctc_merge_repeated=opt.merge, time_major=False)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\ctc_ops.py", line 145, in ctc_loss
    ctc_merge_repeated=ctc_merge_repeated)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\gen_ctc_ops.py", line 164, in _ctc_loss
    name=name)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "C:\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 1 but is rank 0 for 'CTCLoss' (op: 'CTCLoss') with input shapes: [?,4,37], [?,2], [?], [].

**Comment by Kyubyong** [comment]
Try replacing `dims` with `axis` in line 35.

seq_len = tf.not_equal(x.sg_sum(dims=2), 0.).sg_int().sg_sum(dims=1)
