### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dense_shape'

### ISSUE THREAD

**Issue by zessi1990** [buriburisuri/speech-to-text-wavenet#52]
when i use python3.5 , tensoflow 0.12.1 for windows , run train.py

runfile('E:/speech-to-text-wavenet-master/train.py', wdir='E:/speech-to-text-wavenet-master')
Reloaded modules: data
INFO:tensorflow:0310:14:10:48.482:data.py:73] VCTK corpus loaded.(total data=36395, total batch=9098)
Traceback (most recent call last):

  File "<ipython-input-11-e5e201044a30>", line 1, in <module>
    runfile('E:/speech-to-text-wavenet-master/train.py', wdir='E:/speech-to-text-wavenet-master')

  File "d:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "d:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/speech-to-text-wavenet-master/train.py", line 79, in <module>
    loss = logit.sg_ctc(target=y, seq_len=seq_len)

  File "d:\Anaconda3\lib\site-packages\sugartensor-1.0.0.1-py3.5.egg\sugartensor\sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))

  File "d:\Anaconda3\lib\site-packages\sugartensor-1.0.0.1-py3.5.egg\sugartensor\sg_loss.py", line 225, in sg_ctc
    out = tf.nn.ctc_loss(opt.target.sg_to_sparse(), tensor, opt.seq_len,

  File "d:\Anaconda3\lib\site-packages\sugartensor-1.0.0.1-py3.5.egg\sugartensor\sg_main.py", line 151, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))

  File "d:\Anaconda3\lib\site-packages\sugartensor-1.0.0.1-py3.5.egg\sugartensor\sg_transform.py", line 277, in sg_to_sparse
    dense_shape=tf.shape(tensor).sg_cast(dtype=tf.int64))

TypeError: __init__() got an unexpected keyword argument 'dense_shape'

**Comment by Skywola** [comment]
I get this running Linux from code on the getting started page for Tensorflow . . . . so far have not found anything to answer why this is happening.   Do they really even want us to use tensorflow, this is not very good if they want it to be used by most people in ML.

**Comment by wang18706789973** [comment]
Yeah, right. I need download datasets first. I solved it.

But I try to run the file recognize.py
$ python recognize.py --file asset/data/LibriSpeech/test-clean/1089/134686/1089-134686-0000.flac
Traceback (most recent call last):
  File "recognize.py", line 51, in <module>
    wav, _ = librosa.load(tf.sg_arg().file, mono=True, sr=16000)
  File "/home/jianhuw/.local/lib/python2.7/site-packages/librosa/core/audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/jianhuw/.local/lib/python2.7/site-packages/audioread/__init__.py", line 114, in audio_open
    raise NoBackendError()
audioread.NoBackendError

I have meet all requirements;

    tensorflow == 1.0.0
    sugartensor == 1.0.0.2
    pandas >= 0.19.2
    tensorflow == 1.0.0
    sugartensor == 1.0.0.2
    pandas >= 0.19.2
    librosa == 0.5.0
    scikits.audiolab==0.11.0
    librosa == 0.5.0
    scikits.audiolab==0.11.0  .   I asked classmates around and search on the net. They all don't know why and some of them have the same problem. Can you help me?

Thanks!

**Comment by wang18706789973** [comment]
I tried to run the file recognize.py
$ python recognize.py --file asset/data/LibriSpeech/test-clean/1089/134686/1089-134686-0000.flac
Traceback (most recent call last):
  File "recognize.py", line 51, in <module>
    wav, _ = librosa.load(tf.sg_arg().file, mono=True, sr=16000)
  File "/home/jianhuw/.local/lib/python2.7/site-packages/librosa/core/audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/jianhuw/.local/lib/python2.7/site-packages/audioread/__init__.py", line 114, in audio_open
    raise NoBackendError()
audioread.NoBackendError

I have meet all requirements;

tensorflow == 1.0.0

sugartensor == 1.0.0.2

pandas >= 0.19.2

tensorflow == 1.0.0

sugartensor == 1.0.0.2

pandas >= 0.19.2

librosa == 0.5.0

scikits.audiolab==0.11.0

librosa == 0.5.0

scikits.audiolab==0.11.0   .   I asked classmates around and search on the net. They all don't  know why and some of them have the same problem. Can you help me?
Thanks!

**Comment by wang18706789973** [comment]
Thank you. I will try.

**Comment by Skywola** [comment]
I found the problem with my  code .  . that line is not suppose to be entered as code, it was a comment on what was suppose to be printed out when you ran the program, but they had not put it in quotes, so it looked like a line of code to enter.  Took it out and the program ran fine.
