### ISSUE TITLE
recognize error

### ISSUE THREAD

**Issue by dzad** [buriburisuri/speech-to-text-wavenet#53]
when i run recognize.py i got this error. please help!

> Traceback (most recent call last):
  File "recognize.py", line 80, in <module>
    y = tf.sparse_to_dense(decoded[0].indices, decoded[0].get_shape(), decoded[0].values) + 1
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/sparse_ops.py", line 554, in sparse_to_dense
    name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_sparse_ops.py", line 1032, in _sparse_to_dense
    validate_indices=validate_indices, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 504, in apply_op
    values, as_ref=input_arg.is_ref).dtype.name
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 128, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)

**Comment by dzad** [comment]
solution is here [https://github.com/buriburisuri/speech-to-text-wavenet/issues/45](url)
but i got a new error
`Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,128,1] rhs shape= [1,128,29]
         [[Node: save/Assign_220 = Assign[T=DT_FLOAT, _class=["loc:@conv1d_33/W"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv1d_33/W, save/RestoreV2_220)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "recognize.py", line 102, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('asset/train'))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,128,1] rhs shape= [1,128,29]
         [[Node: save/Assign_220 = Assign[T=DT_FLOAT, _class=["loc:@conv1d_33/W"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv1d_33/W, save/RestoreV2_220)]]

Caused by op 'save/Assign_220', defined at:
  File "recognize.py", line 101, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 414, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,128,1] rhs shape= [1,128,29]
         [[Node: save/Assign_220 = Assign[T=DT_FLOAT, _class=["loc:@conv1d_33/W"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](conv1d_33/W, save/RestoreV2_220)]]
`
