### ISSUE TITLE
Cant get pretrained model to work

### ISSUE THREAD

**Issue by saurabhvyas** [buriburisuri/speech-to-text-wavenet#57]
So I noticed that the folder 'asset/train/ckpt/ didnt exist after installing , so I created it manually and extracted pretrained zip file before running recognize.py command with my .wav file as parameter and got the following error
```
saurabhorange@orangepc:~/wavene$ python recognize.py --file test.wav
Traceback (most recent call last):
  File "recognize.py", line 27, in <module>
    data = VCTK(vocabulary_loading=True)
  File "/home/saurabhorange/wavene/data.py", line 45, in __init__
    labels, wave_files = self._load_corpus(data_path)
  File "/home/saurabhorange/wavene/data.py", line 79, in _load_corpus
    index_col=False, delim_whitespace=True)
  File "/home/saurabhorange/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/saurabhorange/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/saurabhorange/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/home/saurabhorange/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/saurabhorange/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
IOError: File asset/data/speaker-info.txt does not exist
saurabhorange@orangepc:~/wavene$ 

```

**Comment by nikhilweee** [comment]
I think you might need to download the datasets first. The VCTK Corpus has a file by the same name.
[speaker-info.txt](https://github.com/buriburisuri/speech-to-text-wavenet/files/961070/speaker-info.txt)

**Comment by wang18706789973** [comment]
I triedto run the file recognize.py
$ python recognize.py --file asset/data/LibriSpeech/test-clean/1089/134686/1089-134686-0000.flac
Traceback (most recent call last):
  File "recognize.py", line 51, in <module>
    wav, _ = librosa.load(tf.sg_arg().file, mono=True, sr=16000)
  File "/home/jianhuw/.local/lib/python2.7/site-packages/librosa/core/audio.py", line 107, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/jianhuw/.local/lib/python2.7/site-packages/audioread/__init__.py", line 114, in audio_open
    raise NoBackendError()
audioread.NoBackendError

I have meet all requirements;

tensorflow == 1.0.0

sugartensor == 1.0.0.2

pandas >= 0.19.2

tensorflow == 1.0.0

sugartensor == 1.0.0.2

pandas >= 0.19.2

librosa == 0.5.0

scikits.audiolab==0.11.0

librosa == 0.5.0

scikits.audiolab==0.11.0   .   I asked classmates around and search on the net. They all don't  know why and some of them have the same problem. Can you help me?
Thanks!

**Comment by nikhilweee** [comment]
Please try `sudo apt-get install libav-tools`.
More details [here](https://github.com/librosa/librosa/issues/219).

**Comment by wang18706789973** [comment]
Thank you very much! It solved.
How can I view the original sentence?
