### ISSUE TITLE
TypeError: reduce_sum() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by liewsanmin** [buriburisuri/speech-to-text-wavenet#66]
Hi,

I am just trying to run the example in the readme:

`python recognize.py --file asset/data/LibriSpeech/test-clean/1089/134686/1089-134686-0000.flac` 

and I'm having the following error:

`Traceback (most recent call last):
  File "recognize.py", line 32, in <module>
    seq_len = tf.not_equal(x.sg_sum(axis=2), 0.).sg_int().sg_sum(axis=1)
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_main.py", line 170, in wrapper
    out = func(tensor, tf.sg_opt(kwargs))
  File "/usr/local/lib/python2.7/site-packages/sugartensor/sg_transform.py", line 334, in sg_sum
    return tf.reduce_sum(tensor, axis=opt.axis, keep_dims=opt.keep_dims, name=opt.name)
TypeError: reduce_sum() got an unexpected keyword argument 'axis'`

I have the following dependencies versions installed:
tensorflow==0.11.0
sugartensor==1.0.0.2
librosa==0.5.0
pandas==0.19.2
scikits.audiolab==0.11.0

Systems I'm having:
OS: OSX Yosemite

Any suggestions?

**Comment by sunjunlishi** [comment]
me too

**Comment by sunjunlishi** [comment]
https://github.com/buriburisuri/speech-to-text-wavenet/issues/48

**Comment by sunjunlishi** [comment]
Dependencies ( VERSION MUST BE MATCHED EXACTLY! )
