### ISSUE TITLE
ERROR: Cannot allocate buffer larger than kint32max for StringOutputStream

### ISSUE THREAD

**Issue by dahlem** [buriburisuri/speech-to-text-wavenet#69]
Hi,

I'm running wavenet on librispeech, vctk, and tedlium + some additional data, which brings the training set ~1M in size. I get the error below. Any idea, how I could solve this issue?

Thank you.
Dominik

I 0504:09:22:29.859:data.py:146] TRAIN set loaded.(total data=979739, total batch=7654)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:17.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:00:18.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:2) -> (device: 2, name: Tesla K80, pci bus id: 0000:00:19.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:3) -> (device: 3, name: Tesla K80, pci bus id: 0000:00:1a.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:4) -> (device: 4, name: Tesla K80, pci bus id: 0000:00:1b.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:5) -> (device: 5, name: Tesla K80, pci bus id: 0000:00:1c.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:6) -> (device: 6, name: Tesla K80, pci bus id: 0000:00:1d.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:7) -> (device: 7, name: Tesla K80, pci bus id: 0000:00:1e.0)
[libprotobuf ERROR google/protobuf/io/zero_copy_stream_impl_lite.cc:173] Cannot allocate buffer larger than kint32max for StringOutputStream.
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    ep_size=data.num_batch, max_ep=500)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/sugartensor/sg_train.py", line 69, in sg_train
    train_func(**opt)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/sugartensor/sg_train.py", line 313, in wrapper
    with sv.managed_session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 788, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 949, in managed_session
    start_standard_services=start_standard_services)
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 707, in prepare_or_wait_for_session
    self._write_graph()
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 610, in _write_graph
    self._logdir, "graph.pbtxt")
  File "/home/ubuntu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/graph_io.py", line 67, in write_graph
    file_io.atomic_write_string_to_file(path, str(graph_def))
ValueError: Unable to convert message to str

**Comment by kaituoxu** [comment]
Have you solved this problem?

**Comment by liyd** [comment]
Have you solved this problem?

**Comment by dahlem** [comment]
@kaituoxu , @liyd : No, I haven't solved the problem yet.

**Comment by kaituoxu** [comment]
This might because the data we load is so big.
I solve this problem by using tensorflow TFRecord and queue.
I cut my big training data into pieces of TFRecord files, then I use a file queue (i.e., tf.train.string_input_producer) to load these files. Because each piece of file is small, so I don't get this error any more.
Besides, I use data queue (i.e., tf.train.batch) to generate batch of data.
Here is my solution project for punctuation prediction using LSTM:
https://github.com/kaituoxu/TF-punctuator

**Comment by Sireer** [comment]
Have you solved this problem?

**Comment by ducvuminh-admicro** [comment]
I also got this Error when run on GPU but when run on other CPU machine this error not be printed. Even though got these Error, I saw my program still run.
