### ISSUE TITLE
Issue predicting with pretrained model

### ISSUE THREAD

**Issue by jmiller656** [buriburisuri/speech-to-text-wavenet#85]
I received the following error when running recognize.py
```
INFO:tensorflow:Restoring parameters from asset/train/model.ckpt-205919
2017-08-08 19:28:41.167142: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key learning_rate not found in checkpoint
Traceback (most recent call last):
  File "recognize.py", line 63, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('asset/train'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key learning_rate not found in checkpoint
	 [[Node: save/RestoreV2_231 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_231/tensor_names, save/RestoreV2_231/shape_and_slices)]]

Caused by op u'save/RestoreV2_231', defined at:
  File "recognize.py", line 62, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key learning_rate not found in checkpoint
	 [[Node: save/RestoreV2_231 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_231/tensor_names, save/RestoreV2_231/shape_and_slices)]]

```

**Comment by sunjunlishi** [comment]
me too

**Comment by mrnobody948** [comment]
and me too.
I'm executing recognize.py in the directory with pre-trained model extracted in <speech-to-text-wavenet_PATH>/asset/train
