### ISSUE TITLE
 if not tf.app.flags.FLAGS.__dict__['__parsed']:  KeyError: '__parsed'

### ISSUE THREAD

**Issue by sbrfarhadi** [buriburisuri/speech-to-text-wavenet#99]
hi
Traceback (most recent call last):
  File "recognize.py", line 90, in <module>
    wav, sr = librosa.load(tf.sg_arg().file, mono=True)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\sugartensor\sg_main.py", line 611, in sg_arg
    if not tf.app.flags.FLAGS.__dict__['__parsed']:
KeyError: '__parsed'

I did a lot of searching but no results were found

**Comment by dizzyname** [comment]
I have same problem with you, which tensorflow versions you use ?

**Comment by dizzyname** [comment]
FYI, i just already pass the problem, using tensorflow 1.4 with cuda 8.0 and cudnn 7.0.5

**Comment by lyraw** [comment]
I got the same problem, is there anyway to fix the problem without changing my tensorflow version?

**Comment by dizzyname** [comment]
![screenshot from 2018-06-04 14-17-48](https://user-images.githubusercontent.com/36620987/40903639-33647a30-6802-11e8-9bc8-cbce61eedf74.png)
Buriburi already explain the requirements, so just follow it. If you don't want changing tensorflow version, you can use virtualenv (virtual environment), but the new problem is on nvidia's driver. Tensorflow with version < 1.5.0 need Cuda 8.0 and Cudnn 6.0, >= 1.5.0 need cuda 9.0 and cudnn 7.0.

**Comment by celbertin** [comment]
I've run into this problem as well, I unfortunately cannot match the exact tensorflow versions since I have CUDA 9.0 and CuDNN 7.2, which I cannot change as they would break other projects I'm working on. Has anyone been able to work around this issue?

**Comment by developomp** [comment]
I'm having the same problem too
